### ISSUE TITLE
Update to jsontableschema-v0.7

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-sql-py#36]
# Overview

The driver should be updated to `jsontableschema-v0.7` changes.
# Tasks
- [ ] fix breaking storage changes
- [ ] add new storage features
- [ ] remove deprecated code
- [ ] fix readme on PyPi

**Comment by roll** [comment]
Requires https://github.com/frictionlessdata/jsontableschema-py/issues/99
